### ISSUE TITLE
Activate CORS

### ISSUE THREAD

**Issue by tanrax** [legomolina/MetroVlcSchedule#1]
If I make a call through Ajax.

`Failed to load https://metrovlcschedule.herokuapp.com/api/v1/stations: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Javascript
``` javascript
$.get( "https://metrovlcschedule.herokuapp.com/api/v1/stations", function( data ) {
    console.log(data)
});
```

**Comment by legomolina** [comment]
Can you post the URL where are you calling the API from?

**Comment by tanrax** [comment]
Veo que eres de Valencia, te contesto en castellano.

Es la misma ruta del ejemplo> https://metrovlcschedule.herokuapp.com/api/v1/stations

Cuando hago la petición GET al servidor que tienes en heroku me indica que no está activado los CORS (https://developer.mozilla.org/es/docs/Web/HTTP/Access_control_CORS). Por lo que no puedo hacer peticiones por medio de Javascript.

Gracias!

**Comment by tanrax** [comment]
Una solución sería añadir lo siguiente en la cabecera
```
Access-Control-Allow-Origin: *
```

**Comment by legomolina** [comment]
Buenas,
Necesito que me digas desde qué URL estás llamando a https://metrovlcschedule.herokuapp.com/api/v1/stations; la que aparece en tu navegador.

**Comment by tanrax** [comment]
https://6doble.programadorwebvalencia.com/test.html

PD: Un proyecto FANTÁSTICO. No entiendo como el repositorio tiene tan pocas estrellas. La documentación es clara, y la idea es muy muy buena. Felicidades

**Comment by legomolina** [comment]
En cuanto tenga un momento incluiré los headers en las request.

Muchas gracias!

**Comment by tanrax** [comment]
Muchas gracias a ti!

**Comment by legomolina** [comment]
Fixed on commit [c003948](https://github.com/legomolina/MetroVlcSchedule/commit/c0039483e2a271b87565b9960c703ac565bbcb91).
