### ISSUE TITLE
Mal formato en JSON de estaciones

### ISSUE THREAD

**Issue by tanrax** [legomolina/MetroVlcSchedule#2]
Actualmente devuelve la siguiente estructura:

```
{1: "Rafelbunyol", 2: "La Pobla de Farnals", 3: "Massamagrell", …}
```

Debería tener el siguiente formato:

```
[
   {
       id: 1,
       name: "Rafelbunyol"
   },
   {
       id: 2,
       name: "La Pobla de Farnals"
   },
   {
       id: 3,
       name: "Massamagrell"
   },
...
]
```

**Comment by legomolina** [comment]
Buenas,
el hecho de que el archivo json de las estaciones esté así es porque es más fácil de trabajar con él.
Puedo intentar que la ruta lo devuelva como dices, o puedes abrir un pull request y hago el merge.

Gracias

**Comment by tanrax** [comment]
He conseguido encontrar una solución con Javascript. Iterando cada uno de las claves del objeto.
No es la forma más católica, pero ya funciona :)
Dejo el código con VueJS por si alguien busca en los issues.
Gracias!!
```javascript
    let that = this
    Vue.http.get('https://metrovlcschedule.herokuapp.com/api/v1/stations').then(response => {
      for (let key of Object.keys(response.body)) {
        console.log(key)
        console.log(response.body[key])
      }
    }, response => {
      // error callback
    })
```
