### ISSUE TITLE
Insuficiencia de datos

### ISSUE THREAD

**Issue by MontyBand** [legomolina/MetroVlcSchedule#3]
Enhorabuena por tu api, me sirvió de gran ayuda hace unos meses con el desarrollo de una aplicación, pero ahora quiero actualizarla y añadir ciertos cambios. Uno de esos cambios debería proporcionármelo tu api, y sería saber el número de línea que ocupa ese destino, para poder jugar con el gráfico y darle una mayor usabilidad a mi aplicación. Encantado implementaría yo ese cambio, pero desconozco php y no puedo trabajar en ello. Muchas gracias por tu api y espero que siga creciendo.

**Comment by legomolina** [comment]
No sé si puedo hacerlo ya que no puedo obtener las líneas. La única forma es obtenerlas de aquí y luego ponerlas en cada uno de los trayectos, pero no sé si puede.

![image](https://user-images.githubusercontent.com/9081996/40547543-83e830c8-6032-11e8-904a-808544e78175.png)
