### ISSUE TITLE
Problema con AJAX en Cards

### ISSUE THREAD

**Issue by leyorgar** [legomolina/MetroVlcSchedule#4]
Cuando realizo una petición GET con Ajax a través de Javascript me sale el problema "Access-Control-Allow-Origin" en la petición en Cards.

Muchas gracias.

**Comment by tanrax** [comment]
Si, yo también lo he comprobado con `https://metrovlcschedule.herokuapp.com/api/v1/card/8564853124/balance`

**Comment by legomolina** [comment]
Los headers están puestos: 
https://github.com/legomolina/MetroVlcSchedule/blob/master/app/controllers/CardsController.php#L14

![image](https://user-images.githubusercontent.com/9081996/41367486-7e6bd098-6f3f-11e8-9cde-b24589e232e3.png)

Si estás haciendo la petición con jQuery hay que añadir `xhrFields: { withCredentials: true }` a la petición:

```
$.ajax({
        url: "url",
        dataType : "json",
        method: "get",
        xhrFields: { withCredentials: true },
        ...
});
```

**Comment by tanrax** [comment]
No consigo que funcione. Utilizo el siguiente código.

``` javascript
$.ajax({
        url: `https://metrovlcschedule.herokuapp.com/api/v1/card/078177304272/balance`,
        success: function (result) {
          console.log(result)
        },
        dataType : "json",
        method: "get",
        xhrFields: { withCredentials: true },
        async: false
      })
```

**Comment by legomolina** [comment]
No funciona porque has puesto 12 números y solo se admiten 10, tal como especifica metro valencia.

**Comment by legomolina** [comment]
He probado esto y funciona correctamente:

```
$.ajax({
        url: `https://metrovlcschedule.herokuapp.com/api/v1/card/8177304272/balance`,
        success: function (result) {
          console.log(result);
        },
		error: function (error) {
    		console.log(error);
		},
        dataType : "json",
        method: "get"
      });
```

**Comment by legomolina** [comment]
¿Podríais confirmar que todo funciona correctamente?

**Comment by tanrax** [comment]
Funciona! Gracias
